# Generated by Django 4.2.3 on 2023-08-18 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("company_email", models.EmailField(max_length=100)),
                ("std_code", models.CharField(max_length=5)),
                ("phone", models.CharField(max_length=15)),
                ("designation", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=100)),
                ("archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
            },
        ),
        migrations.CreateModel(
            name="Organisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("registered_name", models.CharField(max_length=100)),
                ("govt_id", models.CharField(blank=True, max_length=100, null=True)),
                ("billing_address", models.TextField(blank=True, null=True)),
                ("shipping_address", models.TextField(blank=True, null=True)),
                ("industry", models.CharField(blank=True, max_length=50, null=True)),
                ("domain", models.CharField(blank=True, max_length=50, null=True)),
                ("size", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "last_funding_stage",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("last_funding_amount", models.IntegerField(blank=True, null=True)),
                (
                    "funding_currency",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                ("segment", models.CharField(blank=True, max_length=50, null=True)),
                ("archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="organisation_created_by_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="organisation_updated_by_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Organisation",
                "verbose_name_plural": "Organisations",
                "permissions": [("access_organisation", "Can access organisation")],
            },
        ),
    ]
