# Generated by Django 4.2.3 on 2023-08-22 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="company_email",
            new_name="email",
        ),
        migrations.AddField(
            model_name="contact",
            name="organisation",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="client.organisation",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="organisation",
            name="registered_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
