# Generated by Django 4.2.3 on 2023-08-23 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0013_group_created_at_group_created_by_group_updated_at_and_more"),
        ("user", "0003_alter_user_reporting_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="user_group",
                to="auth.group",
            ),
        ),
    ]
