# Generated by Django 4.2.3 on 2023-08-18 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=100)),
                ("url_frontend", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("menu", "Menu"),
                            ("administration", "Administration"),
                            ("feature", "Feature"),
                        ],
                        max_length=100,
                    ),
                ),
                ("archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="rbac.accesscategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "AccessCategory",
                "verbose_name_plural": "AccessCategorys",
            },
        ),
        migrations.CreateModel(
            name="GroupCategoryAccessDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access", models.BooleanField(default=None, null=True)),
                ("view", models.BooleanField(default=None, null=True)),
                ("add", models.BooleanField(default=None, null=True)),
                ("change", models.BooleanField(default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "access_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="rbac.accesscategory",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "GroupCategoryAccessDetail",
                "verbose_name_plural": "GroupCategoryAccessDetails",
            },
        ),
    ]
