# Generated by Django 4.2.3 on 2023-08-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rbac", "0002_accesscategory_default_access"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesscategory",
            name="url_frontend",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
