# Generated by Django 4.2.3 on 2023-08-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rbac", "0003_alter_accesscategory_url_frontend"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesscategory",
            name="content_type",
            field=models.JSONField(blank=True, null=True, verbose_name=list),
        ),
    ]
