# Generated by Django 4.2.3 on 2023-08-18 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency", models.CharField(blank=True, max_length=3, null=True)),
                ("service_fee", models.FloatField(blank=True, null=True)),
                (
                    "service_fee_range",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("retainer_advance", models.BooleanField(blank=True, null=True)),
                ("exclusivity", models.BooleanField(blank=True, null=True)),
                ("source", models.CharField(max_length=100)),
                ("status", models.CharField(default="Unverified", max_length=50)),
                ("is_converted_to_prospect", models.BooleanField(default=0)),
                ("archived", models.BooleanField(default=0)),
                ("created_at", models.DateTimeField(editable=False)),
                ("updated_at", models.DateTimeField()),
                (
                    "created_by",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="lead_created_by_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="client.organisation",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="lead_owner_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "ContactLead",
                "verbose_name_plural": "ContactLeads",
                "permissions": [("access_lead", "Can access Lead")],
            },
        ),
        migrations.CreateModel(
            name="RoleDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role_type", models.CharField(max_length=100)),
                ("budget_range", models.CharField(max_length=100)),
                ("fixed_budget", models.FloatField(blank=True, null=True)),
                ("fixed_budget_ul", models.FloatField(blank=True, null=True)),
                ("esop_rsu", models.CharField(blank=True, max_length=100, null=True)),
                ("region", models.CharField(max_length=100)),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "time_To_fill",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("archived", models.BooleanField(default=0)),
                ("created_at", models.DateTimeField(editable=False)),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "RoleDetail",
                "verbose_name_plural": "RoleDetails",
            },
        ),
        migrations.CreateModel(
            name="Prospect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=100, null=True)),
                ("budget", models.CharField(blank=True, max_length=100, null=True)),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                ("source", models.CharField(max_length=100)),
                ("status", models.CharField(default="Unverified", max_length=50)),
                ("is_converted_to_deal", models.BooleanField(default=0)),
                ("archived", models.BooleanField(default=0)),
                ("created_at", models.DateTimeField(editable=False)),
                ("updated_at", models.DateTimeField()),
                (
                    "created_by",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="prospect_lead_created_by_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="pipedrive.lead",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="client.organisation",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="prospect_owner_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="prospect_updated_by_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Prospect",
                "verbose_name_plural": "Prospects",
                "permissions": [("access_prospect", "Can access prospect")],
            },
        ),
        migrations.AddField(
            model_name="lead",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="pipedrive.roledetail",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="updated_by",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="lead_updated_by_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
